name: hola santiago

on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar nombre
        run: echo "Hola, soy santiago"

      - name: verificar si es de dia o de noche
        run: |
          hora=$(date +%H)
          hora_colombia=$(( (hora + 19) % 24 ))
          if [ $hora_colombia -ge 6 ] && [ $hora_colombia -lt 18 ]; then
            echo "¡Buenos días, parcero!"
          else
            echo "¡Buenas noches, parcero!"
          fi