name: hola Autor validar cambios

on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Info del commmit
        run: |
          echo "Autor, ${{ github.actor }}"
          echo "Hola:  ${{ github.event.head_commit.author.name }}"
          echo "revisando: ${{ github.event.head_commit.message }}"

      - name: verificar si es de dia o de noche
        run: |
          hora=$(date +%H)
          hora_colombia=$(( (hora + 19) % 24 ))
          if [ $hora_colombia -ge 6 ] && [ $hora_colombia -lt 18 ]; then
            echo "¡Buenos días, parcero!"
          else
            echo "¡Buenas noches, parcero!"
          fi

  HolaMundo:
    runs-on: ubuntu-latest
    steps:

      - name: saludo
        run: |
          echo "Hola:  ${{ github.event.head_commit.author.name }} estamos revisando tus cambios"

      - name: Validar existencia py
        run: |
          if [ -f main.py ]; then
            echo "main.py encontrado"
            python3 main.py
          else
            echo "❌ No se encontró main.py"
            exit 1
          fi
